// node database/security/build_privileges.js  -> writes migrations/014_function_privileges.sql and docs/SECURITY_FUNCTION_MATRIX.md
const fs = require("fs"), path = require("path");
const matrix = require("./function_matrix");
const root = path.resolve(__dirname, "../..");
const BUILTIN = new Set(["int", "integer", "bigint", "smallint", "text", "uuid", "date", "boolean", "bool", "numeric", "jsonb", "json", "timestamptz", "timestamp", "double precision", "real"]);
const canon = (t) => t.trim().toLowerCase().replace(/^public\./, "").replace(/\binteger\b/, "int").replace(/\bbool\b/, "boolean");
const qual = (t) => { const b = t.trim().replace(/^public\./, ""); const base = b.replace(/\[\]$/, ""); return (BUILTIN.has(base.toLowerCase()) ? b : "public." + b); };
function splitTop(s) { const out = []; let d = 0, cur = ""; for (const ch of s) { if (ch === "(") d++; if (ch === ")") d--; if (ch === "," && d === 0) { out.push(cur); cur = ""; } else cur += ch; } if (cur.trim()) out.push(cur); return out; }
function parseArgs(a) {
  return splitTop(a).map((x) => x.replace(/\s+/g, " ").trim()).filter(Boolean).map((x) => x.replace(/\s+default\s+.*$/i, "").replace(/^(in|out|inout|variadic)\s+/i, ""))
    .map((x) => { const parts = x.split(" "); return parts.length === 1 ? parts[0] : parts.slice(1).join(" "); });
}
function collect() {
  const dir = path.join(root, "database/migrations"), fns = new Map();
  for (const f of fs.readdirSync(dir).filter((f) => /^\d+_.*\.sql$/.test(f)).sort()) {
    const s = fs.readFileSync(path.join(dir, f), "utf8");
    // process create/drop statements IN FILE ORDER
    const re = /(create\s+(?:or\s+replace\s+)?function\s+(?:public\.)?(\w+)\s*\(([\s\S]*?)\)\s*returns\s+(\w+)([\s\S]*?)\$\$|drop\s+function\s+if\s+exists\s+(?:public\.)?(\w+)\s*\(([^)]*)\))/gi;
    let m;
    while ((m = re.exec(s))) {
      if (m[2]) {
        const head = m[0]; const types = parseArgs(m[3]);
        const key = m[2] + "(" + types.map(canon).join(",") + ")";
        fns.set(key, { name: m[2], types, sd: /security\s+definer/i.test(head), pinned: /set\s+search_path\s*=/i.test(head), trigger: m[4].toLowerCase() === "trigger", file: f, body: s.slice(m.index, Math.max(re.lastIndex, s.indexOf("$$", re.lastIndex) + 2)) });
      } else if (m[6]) {
        fns.delete(m[6] + "(" + parseArgs(m[7]).map(canon).join(",") + ")");
      }
    }
  }
  return [...fns.values()];
}
module.exports = { collect, qual, canon };
if (require.main !== module) return;      // required as a library (validation kit): do not rewrite 014 / the matrix doc
if (require.main !== module) { module.exports = { collect }; return; }
const fns = collect();
const missing = fns.filter((f) => !matrix[f.name]);
if (missing.length) { console.error("UNCLASSIFIED functions:", missing.map((f) => f.name).join(", ")); process.exit(1); }
const sig = (f) => `public.${f.name}(${f.types.map(qual).join(", ")})`;
const by = (cls) => fns.filter((f) => matrix[f.name].cls === cls).map(sig);
const list = (a) => a.map((x) => `    '${x}'`).join(",\n");
const clients = [...by("rpc"), ...by("admin"), ...by("rls"), ...by("pure")];

const sql = `-- 014_function_privileges.sql — Phase 6A. GENERATED by database/security/build_privileges.js from function_matrix.js. Do not edit by hand.
-- SQL NOT EXECUTED when written (no Postgres available). MUST RUN LAST (after 012): it re-derives every function's EXECUTE grants.
--
-- WHY: Postgres grants EXECUTE on new functions to PUBLIC, and Supabase's default privileges also grant it to anon and authenticated.
-- Older migrations revoked selectively; anything not named stayed callable by anon. This migration is an ALLOW-LIST:
--   1. revoke EXECUTE on every function WE own in schema public (extension functions such as pg_trgm are skipped) from PUBLIC, anon, authenticated
--   2. grant back only what the matrix says: client RPCs, RLS helpers and pure helpers -> authenticated; service jobs -> service_role only
--   3. assert the result, and raise (rolling the migration back) if anything is off
-- service_role keeps EXECUTE everywhere (it is never revoked here). Trigger functions need no EXECUTE grant to fire.

do $$ declare r record; begin
  for r in select p.oid::regprocedure as sig from pg_proc p join pg_namespace n on n.oid = p.pronamespace
            where n.nspname = 'public' and p.prokind = 'f'
              and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e') loop
    execute format('revoke all on function %s from public, anon, authenticated', r.sig);
  end loop;
end $$;

-- Future functions created by this role start locked too (each new function must be added to the matrix, then re-run this file).
alter default privileges in schema public revoke execute on functions from public, anon, authenticated;

-- 2a. client-callable (client RPCs, RLS helpers, pure helpers)
do $$ declare f text; p regprocedure; begin
  foreach f in array array[
${list(clients)}
  ] loop
    p := to_regprocedure(f);
    if p is null then raise exception '014: allow-list entry not found: %', f; end if;
    execute format('grant execute on function %s to authenticated', p);
  end loop;
end $$;

-- 2b. service_role only
do $$ declare f text; p regprocedure; begin
  foreach f in array array[
${list(by("service"))}
  ] loop
    p := to_regprocedure(f);
    if p is null then raise exception '014: service-only entry not found: %', f; end if;
    execute format('grant execute on function %s to service_role', p);
  end loop;
end $$;

-- 3. assertions
-- The allow-list is compared as RESOLVED OIDs (to_regprocedure), never as text: regprocedure::text depends on search_path and on type aliases
-- (it prints "set_publish_status(text,uuid,publish_status_t)" with no spaces, "integer" for int, schema-qualified enums when public is not on the path).
do $$ declare r record; n int; v_name text; v_sig regprocedure; v_allowed oid[] := '{}'; begin
  foreach v_name in array array[
${list(clients)}
  ] loop
    v_sig := to_regprocedure(v_name);
    if v_sig is null then raise exception '014: allow-list entry not found: %', v_name; end if;
    v_allowed := v_allowed || v_sig::oid;
  end loop;
  -- nothing of ours is executable by anon (or by the PUBLIC pseudo-role)
  for r in select p.oid::regprocedure as sig from pg_proc p join pg_namespace ns on ns.oid = p.pronamespace
            where ns.nspname = 'public' and p.prokind = 'f' and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')
              and (has_function_privilege('anon', p.oid, 'execute') or has_function_privilege('public', p.oid, 'execute')) loop
    raise exception '014: % is still executable by anon/PUBLIC', r.sig;
  end loop;
  -- no SECURITY DEFINER function is executable by authenticated unless it is on the client allow-list (compared by OID)
  for r in select p.oid::regprocedure as sig from pg_proc p join pg_namespace ns on ns.oid = p.pronamespace
            where ns.nspname = 'public' and p.prokind = 'f' and p.prosecdef and has_function_privilege('authenticated', p.oid, 'execute')
              and p.oid <> all (v_allowed) loop
    raise exception '014: SECURITY DEFINER function % is executable by authenticated but is not on the allow-list', r.sig;
  end loop;
  -- every SECURITY DEFINER function pins its search_path
  select count(*) into n from pg_proc p join pg_namespace ns on ns.oid = p.pronamespace
   where ns.nspname = 'public' and p.prosecdef and not exists (select 1 from unnest(coalesce(p.proconfig, '{}')) c where c like 'search_path=%');
  if n > 0 then raise exception '014: % SECURITY DEFINER function(s) without a pinned search_path', n; end if;
end $$;
`;
fs.writeFileSync(path.join(root, "database/migrations/014_function_privileges.sql"), sql);

const roleText = { rpc: "authenticated", admin: "authenticated (admin only inside)", rls: "authenticated", pure: "authenticated", trigger: "none", internal: "none", service: "service_role" };
const rows = fns.slice().sort((a, b) => a.file.localeCompare(b.file) || a.name.localeCompare(b.name)).map((f) => {
  const m = matrix[f.name];
  return `| \`${f.name}(${f.types.map((t) => t.replace(/^public\./, "")).join(", ")})\` | ${f.sd ? "yes" : "no"} | ${roleText[m.cls]} | ${m.purpose} | ${m.risk} |`;
});
const sdCount = fns.filter((f) => f.sd).length;
const md = `# Function execution matrix (migrations 001-013, enforced by 014)

Generated by \`database/security/build_privileges.js\` from \`function_matrix.js\`. **Not verified against a live database.**
${fns.length} functions, ${sdCount} SECURITY DEFINER. Every SECURITY DEFINER function pins \`search_path\` (checked statically by \`tests/study/security.test.ts\`; 014 re-checks it in SQL).

Rules: no function is executable by \`anon\` or PUBLIC. Functions that take a user or session id and bypass RLS are not executable by clients. \`service_role\` is never revoked.

| FUNCTION | SECURITY DEFINER | EXECUTE ROLES | PURPOSE | RISK |
|---|---|---|---|---|
${rows.join("\n")}
`;
fs.writeFileSync(path.join(root, "docs/SECURITY_FUNCTION_MATRIX.md"), md);
console.log(`${fns.length} functions (${sdCount} SECURITY DEFINER); client=${clients.length} service=${by("service").length} internal=${by("internal").length} trigger=${by("trigger").length}`);
