-- 014_function_privileges.sql — Phase 6A. GENERATED by database/security/build_privileges.js from function_matrix.js. Do not edit by hand.
-- SQL NOT EXECUTED when written (no Postgres available). MUST RUN LAST (after 012): it re-derives every function's EXECUTE grants.
--
-- WHY: Postgres grants EXECUTE on new functions to PUBLIC, and Supabase's default privileges also grant it to anon and authenticated.
-- Older migrations revoked selectively; anything not named stayed callable by anon. This migration is an ALLOW-LIST:
--   1. revoke EXECUTE on every function WE own in schema public (extension functions such as pg_trgm are skipped) from PUBLIC, anon, authenticated
--   2. grant back only what the matrix says: client RPCs, RLS helpers and pure helpers -> authenticated; service jobs -> service_role only
--   3. assert the result, and raise (rolling the migration back) if anything is off
-- service_role keeps EXECUTE everywhere (it is never revoked here). Trigger functions need no EXECUTE grant to fire.

do $$ declare r record; begin
  for r in select p.oid::regprocedure as sig from pg_proc p join pg_namespace n on n.oid = p.pronamespace
            where n.nspname = 'public' and p.prokind = 'f'
              and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e') loop
    execute format('revoke all on function %s from public, anon, authenticated', r.sig);
  end loop;
end $$;

-- Future functions created by this role start locked too (each new function must be added to the matrix, then re-run this file).
alter default privileges in schema public revoke execute on functions from public, anon, authenticated;

-- 2a. client-callable (client RPCs, RLS helpers, pure helpers)
do $$ declare f text; p regprocedure; begin
  foreach f in array array[
    'public.topic_pyq_stats(uuid)',
    'public.subject_pyq_counts(uuid)',
    'public.set_progress(public.entity_t, uuid, text, int, int)',
    'public.study_start(public.entity_t, uuid)',
    'public.study_pause(uuid)',
    'public.study_resume(uuid)',
    'public.study_heartbeat(uuid)',
    'public.study_finish(uuid, int)',
    'public.study_recover()',
    'public.schedule_revision(public.entity_t, uuid)',
    'public.review_revision(uuid, text, int, int)',
    'public.practice_state(uuid)',
    'public.submit_pyq_answer(uuid, uuid, text, int)',
    'public.finish_practice(uuid, boolean)',
    'public.topic_pyqs(uuid, int)',
    'public.active_entities()',
    'public.user_entity_signals(public.entity_t, uuid)',
    'public.daily_focus(int)',
    'public.dashboard_summary()',
    'public.start_practice(text, uuid, int, public.difficulty_t, uuid)',
    'public.practice_options(text, uuid)',
    'public.practice_question(uuid, uuid)',
    'public.global_search(text, int)',
    'public.revision_queue()',
    'public.set_publish_status(text, uuid, public.publish_status_t)',
    'public.verify_source(uuid, boolean)',
    'public.set_exam_official(uuid, boolean)',
    'public.import_create_run(text, text, jsonb, boolean)',
    'public.import_stage_rows(uuid, text, jsonb)',
    'public.import_validate_run(uuid)',
    'public.import_apply_run(uuid)',
    'public.import_discard_run(uuid)',
    'public.is_admin()',
    'public.is_book_visible(uuid)',
    'public.is_chapter_visible(uuid)',
    'public.is_exam_visible(uuid)',
    'public.is_tier_visible(uuid)',
    'public.is_ssc_subject_visible(uuid)',
    'public.is_topic_visible(uuid)',
    'public.search_rank(text, text, text, text)',
    'public.app_now()',
    'public.user_today(uuid)',
    'public.lc_min_attempts()',
    'public.lc_recent_window()',
    'public.lc_weak_accuracy()',
    'public.lc_strong_accuracy()',
    'public.lc_mastered_accuracy()',
    'public.lc_weak_confidence()',
    'public.lc_strong_confidence()',
    'public.lc_hard_streak()',
    'public.lc_default_ladder()',
    'public.lc_max_intervals()',
    'public.lc_max_interval_days()',
    'public.lc_step_good()',
    'public.lc_step_easy()',
    'public.lc_stale_seconds()',
    'public.lc_stale_credit_seconds()',
    'public.lc_min_session_seconds()',
    'public.lc_max_session_seconds()',
    'public.lc_focus_max()',
    'public._require_uid()',
    'public._user_tz(uuid)',
    'public.revision_next(int, text, int[], date)',
    'public._ladder(uuid)',
    'public.pyq_answer_valid(jsonb, text)',
    'public.priority_rank(public.priority_t)',
    'public.learning_weak_reason(int, numeric, int, text[])',
    'public.learning_mastery(text, int, int, int, int, numeric, date, date, text[], int, boolean)'
  ] loop
    p := to_regprocedure(f);
    if p is null then raise exception '014: allow-list entry not found: %', f; end if;
    execute format('grant execute on function %s to authenticated', p);
  end loop;
end $$;

-- 2b. service_role only
do $$ declare f text; p regprocedure; begin
  foreach f in array array[
    'public.entities_integrity_report()',
    'public.study_sweep_stale()'
  ] loop
    p := to_regprocedure(f);
    if p is null then raise exception '014: service-only entry not found: %', f; end if;
    execute format('grant execute on function %s to service_role', p);
  end loop;
end $$;

-- 3. assertions
do $$ declare r record; n int; begin
  -- nothing of ours is executable by anon (or by the PUBLIC pseudo-role)
  for r in select p.oid::regprocedure as sig from pg_proc p join pg_namespace ns on ns.oid = p.pronamespace
            where ns.nspname = 'public' and p.prokind = 'f' and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')
              and (has_function_privilege('anon', p.oid, 'execute') or has_function_privilege('public', p.oid, 'execute')) loop
    raise exception '014: % is still executable by anon/PUBLIC', r.sig;
  end loop;
  -- no SECURITY DEFINER function is executable by authenticated unless it is on the client allow-list
  for r in select p.oid::regprocedure as sig from pg_proc p join pg_namespace ns on ns.oid = p.pronamespace
            where ns.nspname = 'public' and p.prokind = 'f' and p.prosecdef and has_function_privilege('authenticated', p.oid, 'execute')
              and p.oid::regprocedure::text <> all (array[
    'topic_pyq_stats(uuid)',
    'subject_pyq_counts(uuid)',
    'set_progress(public.entity_t, uuid, text, int, int)',
    'study_start(public.entity_t, uuid)',
    'study_pause(uuid)',
    'study_resume(uuid)',
    'study_heartbeat(uuid)',
    'study_finish(uuid, int)',
    'study_recover()',
    'schedule_revision(public.entity_t, uuid)',
    'review_revision(uuid, text, int, int)',
    'practice_state(uuid)',
    'submit_pyq_answer(uuid, uuid, text, int)',
    'finish_practice(uuid, boolean)',
    'topic_pyqs(uuid, int)',
    'active_entities()',
    'user_entity_signals(public.entity_t, uuid)',
    'daily_focus(int)',
    'dashboard_summary()',
    'start_practice(text, uuid, int, public.difficulty_t, uuid)',
    'practice_options(text, uuid)',
    'practice_question(uuid, uuid)',
    'global_search(text, int)',
    'revision_queue()',
    'set_publish_status(text, uuid, public.publish_status_t)',
    'verify_source(uuid, boolean)',
    'set_exam_official(uuid, boolean)',
    'import_create_run(text, text, jsonb, boolean)',
    'import_stage_rows(uuid, text, jsonb)',
    'import_validate_run(uuid)',
    'import_apply_run(uuid)',
    'import_discard_run(uuid)',
    'is_admin()',
    'is_book_visible(uuid)',
    'is_chapter_visible(uuid)',
    'is_exam_visible(uuid)',
    'is_tier_visible(uuid)',
    'is_ssc_subject_visible(uuid)',
    'is_topic_visible(uuid)',
    'search_rank(text, text, text, text)',
    'app_now()',
    'user_today(uuid)',
    'lc_min_attempts()',
    'lc_recent_window()',
    'lc_weak_accuracy()',
    'lc_strong_accuracy()',
    'lc_mastered_accuracy()',
    'lc_weak_confidence()',
    'lc_strong_confidence()',
    'lc_hard_streak()',
    'lc_default_ladder()',
    'lc_max_intervals()',
    'lc_max_interval_days()',
    'lc_step_good()',
    'lc_step_easy()',
    'lc_stale_seconds()',
    'lc_stale_credit_seconds()',
    'lc_min_session_seconds()',
    'lc_max_session_seconds()',
    'lc_focus_max()',
    '_require_uid()',
    '_user_tz(uuid)',
    'revision_next(int, text, int[], date)',
    '_ladder(uuid)',
    'pyq_answer_valid(jsonb, text)',
    'priority_rank(public.priority_t)',
    'learning_weak_reason(int, numeric, int, text[])',
    'learning_mastery(text, int, int, int, int, numeric, date, date, text[], int, boolean)'
  ]) loop
    raise exception '014: SECURITY DEFINER function % is executable by authenticated but is not on the allow-list', r.sig;
  end loop;
  -- every SECURITY DEFINER function pins its search_path
  select count(*) into n from pg_proc p join pg_namespace ns on ns.oid = p.pronamespace
   where ns.nspname = 'public' and p.prosecdef and not exists (select 1 from unnest(coalesce(p.proconfig, '{}')) c where c like 'search_path=%');
  if n > 0 then raise exception '014: % SECURITY DEFINER function(s) without a pinned search_path', n; end if;
end $$;
