-- 014_function_privileges.sql — Phase 6A. GENERATED by database/security/build_privileges.js from function_matrix.js. Do not edit by hand.
-- SQL NOT EXECUTED when written (no Postgres available). MUST RUN LAST (after 012): it re-derives every function's EXECUTE grants.
--
-- WHY: Postgres grants EXECUTE on new functions to PUBLIC, and Supabase's default privileges also grant it to anon and authenticated.
-- Older migrations revoked selectively; anything not named stayed callable by anon. This migration is an ALLOW-LIST:
--   1. revoke EXECUTE on every function WE own in schema public (extension functions such as pg_trgm are skipped) from PUBLIC, anon, authenticated
--   2. grant back only what the matrix says: client RPCs, RLS helpers and pure helpers -> authenticated; service jobs -> service_role only
--   2c. (tables) remove TRUNCATE / REFERENCES / TRIGGER from anon and authenticated on every public table (RLS cannot protect against TRUNCATE)
--   3. assert the result, and raise (rolling the migration back) if anything is off
-- service_role keeps EXECUTE everywhere (it is never revoked here). Trigger functions need no EXECUTE grant to fire.

do $$ declare r record; begin
  for r in select p.oid::regprocedure as sig from pg_proc p join pg_namespace n on n.oid = p.pronamespace
            where n.nspname = 'public' and p.prokind = 'f'
              and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e') loop
    execute format('revoke all on function %s from public, anon, authenticated', r.sig);
  end loop;
end $$;

-- Future functions created by this role start locked too (each new function must be added to the matrix, then re-run this file).
alter default privileges in schema public revoke execute on functions from public, anon, authenticated;

-- 2a. client-callable (client RPCs, RLS helpers, pure helpers)
do $$ declare f text; p regprocedure; begin
  foreach f in array array[
    'public.topic_pyq_stats(uuid)',
    'public.subject_pyq_counts(uuid)',
    'public.set_progress(public.entity_t, uuid, text, int, int)',
    'public.study_start(public.entity_t, uuid)',
    'public.study_pause(uuid)',
    'public.study_resume(uuid)',
    'public.study_heartbeat(uuid)',
    'public.study_finish(uuid, int)',
    'public.study_recover()',
    'public.schedule_revision(public.entity_t, uuid)',
    'public.review_revision(uuid, text, int, int)',
    'public.practice_state(uuid)',
    'public.submit_pyq_answer(uuid, uuid, text, int)',
    'public.finish_practice(uuid, boolean)',
    'public.topic_pyqs(uuid, int)',
    'public.active_entities()',
    'public.user_entity_signals(public.entity_t, uuid)',
    'public.daily_focus(int)',
    'public.dashboard_summary()',
    'public.start_practice(text, uuid, int, public.difficulty_t, uuid)',
    'public.practice_options(text, uuid)',
    'public.practice_question(uuid, uuid)',
    'public.global_search(text, int)',
    'public.revision_queue()',
    'public.set_publish_status(text, uuid, public.publish_status_t)',
    'public.verify_source(uuid, boolean)',
    'public.set_exam_official(uuid, boolean)',
    'public.import_create_run(text, text, jsonb, boolean)',
    'public.import_stage_rows(uuid, text, jsonb)',
    'public.import_validate_run(uuid)',
    'public.import_apply_run(uuid)',
    'public.import_discard_run(uuid)',
    'public.is_admin()',
    'public.is_book_visible(uuid)',
    'public.is_chapter_visible(uuid)',
    'public.is_exam_visible(uuid)',
    'public.is_tier_visible(uuid)',
    'public.is_ssc_subject_visible(uuid)',
    'public.is_topic_visible(uuid)',
    'public.search_rank(text, text, text, text)',
    'public.app_now()',
    'public.user_today(uuid)',
    'public.lc_min_attempts()',
    'public.lc_recent_window()',
    'public.lc_weak_accuracy()',
    'public.lc_strong_accuracy()',
    'public.lc_mastered_accuracy()',
    'public.lc_weak_confidence()',
    'public.lc_strong_confidence()',
    'public.lc_hard_streak()',
    'public.lc_default_ladder()',
    'public.lc_max_intervals()',
    'public.lc_max_interval_days()',
    'public.lc_step_good()',
    'public.lc_step_easy()',
    'public.lc_stale_seconds()',
    'public.lc_stale_credit_seconds()',
    'public.lc_min_session_seconds()',
    'public.lc_max_session_seconds()',
    'public.lc_focus_max()',
    'public._require_uid()',
    'public._user_tz(uuid)',
    'public.revision_next(int, text, int[], date)',
    'public._ladder(uuid)',
    'public.pyq_answer_valid(jsonb, text)',
    'public.priority_rank(public.priority_t)',
    'public.learning_weak_reason(int, numeric, int, text[])',
    'public.learning_mastery(text, int, int, int, int, numeric, date, date, text[], int, boolean)'
  ] loop
    p := to_regprocedure(f);
    if p is null then raise exception '014: allow-list entry not found: %', f; end if;
    execute format('grant execute on function %s to authenticated', p);
  end loop;
end $$;

-- 2b. service_role only
do $$ declare f text; p regprocedure; begin
  foreach f in array array[
    'public.entities_integrity_report()',
    'public.study_sweep_stale()'
  ] loop
    p := to_regprocedure(f);
    if p is null then raise exception '014: service-only entry not found: %', f; end if;
    execute format('grant execute on function %s to service_role', p);
  end loop;
end $$;

-- 2c. TABLE privileges that Row Level Security does NOT cover. Supabase's default privileges (and the CI bootstrap that mimics them) grant ALL on every new table to
-- anon and authenticated, including TRUNCATE (RLS never applies to it), REFERENCES and TRIGGER. Clients never need these three. Row access stays governed by RLS and by the
-- explicit revokes of earlier migrations; this removes only the non-DML privileges, for existing tables and for tables created later by this role.
revoke truncate, references, trigger on all tables in schema public from anon, authenticated;
alter default privileges in schema public revoke truncate, references, trigger on tables from anon, authenticated;

-- 3. assertions
-- The allow-list is compared as RESOLVED OIDs (to_regprocedure), never as text: regprocedure::text depends on search_path and on type aliases
-- (it prints "set_publish_status(text,uuid,publish_status_t)" with no spaces, "integer" for int, schema-qualified enums when public is not on the path).
do $$ declare r record; n int; v_name text; v_sig regprocedure; v_allowed oid[] := '{}'; begin
  foreach v_name in array array[
    'public.topic_pyq_stats(uuid)',
    'public.subject_pyq_counts(uuid)',
    'public.set_progress(public.entity_t, uuid, text, int, int)',
    'public.study_start(public.entity_t, uuid)',
    'public.study_pause(uuid)',
    'public.study_resume(uuid)',
    'public.study_heartbeat(uuid)',
    'public.study_finish(uuid, int)',
    'public.study_recover()',
    'public.schedule_revision(public.entity_t, uuid)',
    'public.review_revision(uuid, text, int, int)',
    'public.practice_state(uuid)',
    'public.submit_pyq_answer(uuid, uuid, text, int)',
    'public.finish_practice(uuid, boolean)',
    'public.topic_pyqs(uuid, int)',
    'public.active_entities()',
    'public.user_entity_signals(public.entity_t, uuid)',
    'public.daily_focus(int)',
    'public.dashboard_summary()',
    'public.start_practice(text, uuid, int, public.difficulty_t, uuid)',
    'public.practice_options(text, uuid)',
    'public.practice_question(uuid, uuid)',
    'public.global_search(text, int)',
    'public.revision_queue()',
    'public.set_publish_status(text, uuid, public.publish_status_t)',
    'public.verify_source(uuid, boolean)',
    'public.set_exam_official(uuid, boolean)',
    'public.import_create_run(text, text, jsonb, boolean)',
    'public.import_stage_rows(uuid, text, jsonb)',
    'public.import_validate_run(uuid)',
    'public.import_apply_run(uuid)',
    'public.import_discard_run(uuid)',
    'public.is_admin()',
    'public.is_book_visible(uuid)',
    'public.is_chapter_visible(uuid)',
    'public.is_exam_visible(uuid)',
    'public.is_tier_visible(uuid)',
    'public.is_ssc_subject_visible(uuid)',
    'public.is_topic_visible(uuid)',
    'public.search_rank(text, text, text, text)',
    'public.app_now()',
    'public.user_today(uuid)',
    'public.lc_min_attempts()',
    'public.lc_recent_window()',
    'public.lc_weak_accuracy()',
    'public.lc_strong_accuracy()',
    'public.lc_mastered_accuracy()',
    'public.lc_weak_confidence()',
    'public.lc_strong_confidence()',
    'public.lc_hard_streak()',
    'public.lc_default_ladder()',
    'public.lc_max_intervals()',
    'public.lc_max_interval_days()',
    'public.lc_step_good()',
    'public.lc_step_easy()',
    'public.lc_stale_seconds()',
    'public.lc_stale_credit_seconds()',
    'public.lc_min_session_seconds()',
    'public.lc_max_session_seconds()',
    'public.lc_focus_max()',
    'public._require_uid()',
    'public._user_tz(uuid)',
    'public.revision_next(int, text, int[], date)',
    'public._ladder(uuid)',
    'public.pyq_answer_valid(jsonb, text)',
    'public.priority_rank(public.priority_t)',
    'public.learning_weak_reason(int, numeric, int, text[])',
    'public.learning_mastery(text, int, int, int, int, numeric, date, date, text[], int, boolean)'
  ] loop
    v_sig := to_regprocedure(v_name);
    if v_sig is null then raise exception '014: allow-list entry not found: %', v_name; end if;
    v_allowed := v_allowed || v_sig::oid;
  end loop;
  -- nothing of ours is executable by anon (or by the PUBLIC pseudo-role)
  for r in select p.oid::regprocedure as sig from pg_proc p join pg_namespace ns on ns.oid = p.pronamespace
            where ns.nspname = 'public' and p.prokind = 'f' and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')
              and (has_function_privilege('anon', p.oid, 'execute') or has_function_privilege('public', p.oid, 'execute')) loop
    raise exception '014: % is still executable by anon/PUBLIC', r.sig;
  end loop;
  -- no SECURITY DEFINER function is executable by authenticated unless it is on the client allow-list (compared by OID)
  for r in select p.oid::regprocedure as sig from pg_proc p join pg_namespace ns on ns.oid = p.pronamespace
            where ns.nspname = 'public' and p.prokind = 'f' and p.prosecdef and has_function_privilege('authenticated', p.oid, 'execute')
              and p.oid <> all (v_allowed) loop
    raise exception '014: SECURITY DEFINER function % is executable by authenticated but is not on the allow-list', r.sig;
  end loop;
  -- no client role can TRUNCATE (or REFERENCE / TRIGGER on) any table in schema public
  for r in select c.oid::regclass as tbl, rl.rolname from pg_class c join pg_namespace ns on ns.oid = c.relnamespace cross join (values ('anon'), ('authenticated')) rl(rolname)
            where ns.nspname = 'public' and c.relkind in ('r', 'p') and has_table_privilege(rl.rolname, c.oid, 'truncate, references, trigger') loop
    raise exception '014: % still has TRUNCATE/REFERENCES/TRIGGER on %', r.rolname, r.tbl;
  end loop;
  -- every SECURITY DEFINER function pins its search_path
  select count(*) into n from pg_proc p join pg_namespace ns on ns.oid = p.pronamespace
   where ns.nspname = 'public' and p.prosecdef and not exists (select 1 from unnest(coalesce(p.proconfig, '{}')) c where c like 'search_path=%');
  if n > 0 then raise exception '014: % SECURITY DEFINER function(s) without a pinned search_path', n; end if;
end $$;
