// Cross-platform builder for the runnable SQL suites (no bash, no python). Output for phase4/6/7 is BYTE-IDENTICAL to what the existing
// database/tests/*/build_all.sh scripts produce (checked by `node scripts/validate/sqlbuild.mjs --check`). Tokens @NAME@ become deterministic UUIDv5s.
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
const require = createRequire(import.meta.url);
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const T = (...p) => path.join(root, "database/tests", ...p);
const read = (f) => fs.readFileSync(f, "utf8");

const RESULTS = `
-- ======================= RESULTS =======================
select count(*) filter (where passed) as passed, count(*) filter (where not passed) as failed, count(*) as total from t_results;
select n, label, detail from t_results where not passed order by n;      -- empty = everything passed
select n, case when passed then 'PASS' else 'FAIL' end as result, label from t_results order by n;
rollback;
`;
const NS_DNS = Buffer.from("6ba7b8109dad11d180b400c04fd430c8", "hex");
export function uuid5(name) {
  const h = crypto.createHash("sha1").update(Buffer.concat([NS_DNS, Buffer.from(name, "utf8")])).digest();
  const b = Buffer.from(h.subarray(0, 16)); b[6] = (b[6] & 0x0f) | 0x50; b[8] = (b[8] & 0x3f) | 0x80;
  const x = b.toString("hex"); return `${x.slice(0, 8)}-${x.slice(8, 12)}-${x.slice(12, 16)}-${x.slice(16, 20)}-${x.slice(20)}`;
}
function substitute(text) {
  const tokens = [...new Set([...text.matchAll(/@([A-Z0-9]+)@/g)].map((m) => m[1]))].sort();
  for (const t of tokens) text = text.split(`@${t}@`).join(uuid5("cgl-command-test-" + t));
  const left = text.match(/@[A-Z0-9]+@/g); if (left) throw new Error("unsubstituted tokens: " + [...new Set(left)].join(","));
  return { text, tokens: tokens.length };
}
function ensureVectors() {
  const v = T("reference/generated_vectors.sql");
  if (!fs.existsSync(v)) throw new Error("database/tests/reference/generated_vectors.sql is missing: run `node database/tests/reference/run_reference_tests.js`");
  return read(v);
}
const phase4Parts = ["00_harness.sql", "05_integrity.sql", "06_registry.sql", "07_progress_sessions.sql", "08_revision.sql", "09_pyq.sql", "10_signals.sql", "11_publishing_import.sql"];
export const SUITES = {
  phase4: { label: "Phase 4", out: T("phase4/phase4_all.sql"), build() { let text = phase4Parts.map((p) => read(T("phase4", p))).join("\n"); text = text.replace("\\ir ../reference/generated_vectors.sql", ensureVectors()); return substitute(text + RESULTS); } },
  phase6: { label: "Phase 6", out: T("phase6/phase6_all.sql"), build() { const h = read(T("phase4/00_harness.sql")).replace("\\ir ../reference/generated_vectors.sql", ""); return substitute(h + "\n" + read(T("phase6/12_practice_security.sql")) + RESULTS); } },
  phase7: { label: "Phase 7", out: T("phase7/phase7_all.sql"), build() { const h = read(T("phase4/00_harness.sql")).replace("\\ir ../reference/generated_vectors.sql", ""); return substitute(h + "\n" + read(T("phase7/13_revision.sql")) + RESULTS); } },
  security: { label: "Security regression", out: T("security/security_all.sql"), build() { const h = read(T("phase4/00_harness.sql")).replace("\\ir ../reference/generated_vectors.sql", ""); return substitute(h + "\n" + securityCatalogSql() + "\n" + read(T("security/14_security_regression.sql")) + RESULTS); } },
};
/** Catalog-driven privilege checks generated from function_matrix.js + the migrations (the same inputs 014 is generated from). */
export function securityCatalogSql() {
  const { collect, qual } = require(path.join(root, "database/security/build_privileges.js"));
  const matrix = require(path.join(root, "database/security/function_matrix.js"));
  const AUTH = new Set(["rpc", "admin", "rls", "pure"]);
  const rows = collect().map((f) => {
    const cls = matrix[f.name]?.cls; if (!cls) throw new Error(`function ${f.name} is not classified in function_matrix.js`);
    return { sig: `public.${f.name}(${f.types.map(qual).join(",")})`, name: f.name, cls, auth: AUTH.has(cls), svc: cls === "service" };
  });
  const q = (s) => "'" + s.replace(/'/g, "''") + "'";
  return `-- ---- SEC catalog (generated by scripts/validate/sqlbuild.mjs from function_matrix.js; ${rows.length} functions) ----
create temp table t_fn_expect (sig text, name text, cls text, auth_exec boolean, svc_only boolean);
insert into t_fn_expect values
${rows.map((r) => `  (${q(r.sig)}, ${q(r.name)}, ${q(r.cls)}, ${r.auth}, ${r.svc})`).join(",\n")};
`;
}
export function buildSuite(key) { const s = SUITES[key]; const r = s.build(); fs.writeFileSync(s.out, r.text); return { key, file: s.out, tokens: r.tokens, bytes: Buffer.byteLength(r.text) }; }
export function checkSuite(key) { const s = SUITES[key]; if (!fs.existsSync(s.out)) return { key, ok: false, why: "built file missing" }; const want = s.build().text; return { key, ok: read(s.out) === want, why: read(s.out) === want ? "" : "committed file differs from a fresh build" }; }
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes("--check"); let bad = 0;
  for (const k of Object.keys(SUITES)) {
    if (check) { const r = checkSuite(k); console.log(`${r.ok ? "identical" : "DIFFERS  "} ${k}${r.why ? ": " + r.why : ""}`); if (!r.ok) bad++; }
    else { const r = buildSuite(k); console.log(`built ${path.relative(root, r.file)} (${r.tokens} tokens, ${r.bytes} bytes)`); }
  }
  process.exit(bad ? 1 : 0);
}
